-- ==============================================================================
-- MIGRACIÓN OFICIAL: BANCO DE 120 PREGUNTAS APROBADO PARA DUELO DE EQUIPOS
-- Pueblan las 120 preguntas oficiales (M1 a M15, 8 preguntas por módulo)
-- en public.online_questions_truth con sus respuestas correctas y explicaciones pedagógicas.
-- ==============================================================================

-- 1. Asegurar columnas en online_questions_truth
ALTER TABLE public.online_questions_truth
ADD COLUMN IF NOT EXISTS explanation TEXT;

-- 2. Upsert de las 120 preguntas oficiales
INSERT INTO public.online_questions_truth (id, module_id, correct_answer, explanation) VALUES
    ('duel_m01_q01', 1, 0, 'Un programa es un conjunto ordenado de instrucciones que guían a la computadora paso a paso para realizar una tarea o resolver un problema determinado.'),
    ('duel_m01_q02', 1, 1, 'Python lee y ejecuta las instrucciones en orden secuencial (de arriba hacia abajo). En la primera línea la variable ''precio'' todavía no existe en memoria, produciendo un error.'),
    ('duel_m01_q03', 1, 2, 'La suma y transformación de los datos para obtener el total a pagar es el procesamiento lógico (Proceso) dentro del esquema clásico Entrada - Proceso - Salida.'),
    ('duel_m01_q04', 1, 3, 'El intérprete de Python lee el código fuente instrucción por instrucción, lo traduce a un formato ejecutable y lo lleva a cabo en tiempo real.'),
    ('duel_m01_q05', 1, 0, 'Los algoritmos son deterministas: ante las mismas entradas y las mismas instrucciones, el camino y el resultado siempre son idénticos.'),
    ('duel_m01_q06', 1, 1, 'Para poder sumar dos calificaciones (Proceso), es un requisito indispensable haber obtenido previamente ambos valores (Entrada).'),
    ('duel_m01_q07', 1, 2, 'La Salida es el resultado final generado por el algoritmo para ser comunicado al usuario (en este caso, el sueldo neto mostrado en el recibo).'),
    ('duel_m01_q08', 1, 3, 'Python procesa de arriba hacia abajo. En la línea 1, las variables subtotal y envio aún no existen, provocando un error de nombre (NameError).'),
    ('duel_m02_q01', 2, 0, 'Un algoritmo debe ser preciso (indicar el orden exacto de cada paso), definido (producir el mismo resultado ante los mismos datos) y finito (tener un fin determinado).'),
    ('duel_m02_q02', 2, 1, 'Las instrucciones de un algoritmo deben ser completamente precisas y no dejar lugar a dudas o interpretaciones subjetivas.'),
    ('duel_m02_q03', 2, 2, 'El seguimiento paso a paso es: puntos comienza en 10. Luego 10 + 5 = 15. Finalmente 15 * 2 = 30. Se imprime 30.'),
    ('duel_m02_q04', 2, 3, 'Antes de dividir el total entre 3, es indispensable haber calculado la suma de las tres calificaciones para obtener dicho total.'),
    ('duel_m02_q05', 2, 0, 'La división por cero es una operación matemática indefinida que detiene cualquier programa. Por ello, el tiempo debe ser mayor a cero.'),
    ('duel_m02_q06', 2, 1, 'Se asigna base = 4 y altura = 5. La variable superficie almacena el producto 4 * 5 = 20. Se imprime 20.'),
    ('duel_m02_q07', 2, 2, 'precio_con_descuento = 100 - 20 = 80. impuesto = 80 * 0.10 = 8.0. total = 80 + 8.0 = 88.0.'),
    ('duel_m02_q08', 2, 3, 'Al escribir ''venta - stock'' calcula 10 - 50 = -40. Lo correcto era restar la venta al stock: ''stock = stock - venta'', dando 40.'),
    ('duel_m03_q01', 3, 0, 'Las líneas que comienzan con el símbolo # son comentarios ignorados por el intérprete. Solo se ejecuta print(''B'').'),
    ('duel_m03_q02', 3, 1, 'Python distingue mayúsculas de minúsculas (case-sensitive). ''dato'' y ''Dato'' son dos variables distintas e independientes.'),
    ('duel_m03_q03', 3, 2, 'Los archivos de código fuente de Python utilizan la extensión ''.py'' para que el sistema y el intérprete los identifiquen correctamente.'),
    ('duel_m03_q04', 3, 3, '''if'' es una palabra reservada por Python para las estructuras condicionales y no puede ser utilizada como nombre de variable.'),
    ('duel_m03_q05', 3, 0, 'Si se abren comillas para definir una cadena de texto, es obligatorio cerrarlas antes de cerrar el paréntesis. Si no, se genera un SyntaxError.'),
    ('duel_m03_q06', 3, 1, 'La consola interactiva evalúa instrucciones inmediatas que se pierden al salir, mientras que un script (.py) almacena el código de manera persistente.'),
    ('duel_m03_q07', 3, 2, 'La línea ''# a = a + 10'' está comentada y no tiene efecto. Por ende a vale 5, luego a = 5 * 2 = 10. Se imprime 10.'),
    ('duel_m03_q08', 3, 3, 'En Python los identificadores de variables deben ser una única palabra continua. Para separar palabras se debe utilizar guion bajo (mi_puntaje).'),
    ('duel_m04_q01', 4, 0, 'Una variable es una posición de memoria identificada con un nombre donde se guarda un valor para ser leído o modificado durante la ejecución.'),
    ('duel_m04_q02', 4, 1, 'El operador = asigna el valor numérico 15 a la variable x. La instrucción print(x) muestra su contenido numérico: 15.'),
    ('duel_m04_q03', 4, 2, 'En Python la asignación es destructiva: cada nueva asignación sobrescribe el valor previo. El último valor asignado fue 20.'),
    ('duel_m04_q04', 4, 3, 'Los nombres de variables en Python no pueden comenzar con un dígito numérico. Deben iniciar con una letra o un guion bajo.'),
    ('duel_m04_q05', 4, 0, 'Al hacer ''b = a'', b recibe una copia del valor actual de a (10). Cambiar posteriormente ''a = 99'' no afecta el valor que ya tenía b.'),
    ('duel_m04_q06', 4, 1, 'No se puede utilizar una variable en el lado derecho de una asignación si no ha sido definida y asignada previamente (NameError).'),
    ('duel_m04_q07', 4, 2, 'aux guarda 3. Luego x pasa a valer 8. Finalmente y toma el valor de aux (3). Los valores quedaron intercambiados: x=8, y=3.'),
    ('duel_m04_q08', 4, 3, '100 - 30 = 70. Luego 70 + 10 = 80. Luego 80 - 5 = 75. Se imprime 75.'),
    ('duel_m05_q01', 5, 0, 'Los números sin parte decimal pertenecen al tipo int (integer o entero).'),
    ('duel_m05_q02', 5, 1, 'Los números con parte fraccionaria o decimal se representan con el tipo de dato float.'),
    ('duel_m05_q03', 5, 2, 'La presencia de comillas convierte al valor en una cadena de texto (str), impidiendo realizar operaciones aritméticas directas con números.'),
    ('duel_m05_q04', 5, 3, 'True y False son literales del tipo booleano, cuya clase en Python es ''bool''.'),
    ('duel_m05_q05', 5, 0, 'Python requiere que los literales booleanos inicien con mayúscula (True, False). Escribir ''true'' en minúsculas es interpretado como una variable no definida.'),
    ('duel_m05_q06', 5, 1, 'Cuando el operador + se aplica entre dos cadenas de texto, realiza la concatenación (unión de textos), produciendo ''2030''.'),
    ('duel_m05_q07', 5, 2, 'Python no convierte tipos implícitamente en el operador +. No se puede sumar un str con un int; se debe convertir explícitamente con str(50).'),
    ('duel_m05_q08', 5, 3, 'Python tiene tipado dinámico: una misma variable puede cambiar de tipo de dato si se le reasigna un nuevo valor de otro tipo.'),
    ('duel_m06_q01', 6, 0, '15 - 7 = 8. Se imprime el valor 8.'),
    ('duel_m06_q02', 6, 1, 'En Python el operador de multiplicación es el asterisco (*).'),
    ('duel_m06_q03', 6, 2, 'El operador / siempre realiza la división real (con decimales) devolviendo un valor de tipo float: 7 / 2 = 3.5.'),
    ('duel_m06_q04', 6, 3, 'El operador // calcula el cociente entero de la división, descartando la parte decimal: 14 // 3 = 4.'),
    ('duel_m06_q05', 6, 0, 'El operador % devuelve el resto de la división entera. 19 dividido 4 es 4 con resto 3 (4 * 4 + 3 = 19).'),
    ('duel_m06_q06', 6, 1, 'Por reglas de precedencia matemática estándar, la multiplicación se evalúa antes que la suma: 3 * 4 = 12, y 2 + 12 = 14.'),
    ('duel_m06_q07', 6, 2, 'Los paréntesis alteran la precedencia obligando a evaluar primero lo que encierran: (2 + 3) = 5, y luego 5 * 4 = 20.'),
    ('duel_m06_q08', 6, 3, '23 % 5 da 3 (porque 5 * 4 = 20, resto 3). 10 // 3 da 3. Luego la suma es 3 + 3 = 6.'),
    ('duel_m07_q01', 7, 0, 'El signo simple = es el operador de asignación. El signo doble == es el operador relacional de comparación de igualdad.'),
    ('duel_m07_q02', 7, 1, 'El operador != pregunta si los valores son diferentes. Como 10 es igual a 10, la afirmación de que son diferentes es falsa (False).'),
    ('duel_m07_q03', 7, 2, 'El operador <= es verdadero si el primer valor es menor o si es igual al segundo. Al ser iguales, da True.'),
    ('duel_m07_q04', 7, 3, 'Se compara si 8 > 12. Como 8 no es mayor que 12, la comparación evalúa a False.'),
    ('duel_m07_q05', 7, 0, 'En Python el signo = solo asigna valores y no puede colocarse como expresión dentro de print o de una condición. La comparación requiere ==.'),
    ('duel_m07_q06', 7, 1, 'Las cadenas se comparan carácter por carácter de forma exacta. Debido a la mayúscula inicial (''P'' vs ''p''), las palabras no son iguales (False).'),
    ('duel_m07_q07', 7, 2, '25 % 2 calcula el resto de dividir 25 por 2, que es 1. Luego 1 == 0 evalúa a False. (Comprueba si 25 es par).'),
    ('duel_m07_q08', 7, 3, 'x + 10 evalúa a 20. Luego 20 == y (20 == 20) es True. Se asigna True a resultado y se imprime.'),
    ('duel_m08_q01', 8, 0, 'La conjunción lógica and exige que todas las proposiciones involucradas sean verdaderas simultáneamente para resultar True.'),
    ('duel_m08_q02', 8, 1, 'La disyunción lógica or es verdadera si al menos una de las condiciones es verdadera. Solo es False si ambas son falsas.'),
    ('duel_m08_q03', 8, 2, 'El operador unario not invierte el valor de verdad booleano: convierte False en True y True en False.'),
    ('duel_m08_q04', 8, 3, 'edad >= 18 es 16 >= 18 (False). Como la primera condición es False, el and completo resulta False.'),
    ('duel_m08_q05', 8, 0, 'En una operación con or, al ser tiene_cupon verdadero (True), la expresión completa evalúa a True.'),
    ('duel_m08_q06', 8, 1, '5 > 10 es False. Al aplicar not a False, el resultado final se invierte y es True.'),
    ('duel_m08_q07', 8, 2, 'nota >= 4 es 7 >= 4 (True). nota <= 10 es 7 <= 10 (True). True and True resulta True.'),
    ('duel_m08_q08', 8, 3, '(a or b) es True or False = True. not c es not False = True. Luego True and True da True.'),
    ('duel_m09_q01', 9, 0, 'print() muestra el texto literal en la consola sin incluir las comillas delimitadoras.'),
    ('duel_m09_q02', 9, 1, 'Al no tener comillas, Python busca la variable llamada mensaje y muestra su contenido guardado.'),
    ('duel_m09_q03', 9, 2, 'Cuando print() recibe varios argumentos separados por coma, los muestra separados por un espacio en blanco por defecto.'),
    ('duel_m09_q04', 9, 3, 'La primera instrucción imprime la letra literal ''x''. La segunda instrucción imprime el valor numérico 5 de la variable x.'),
    ('duel_m09_q05', 9, 0, 'Por defecto, cada llamada a la función print() concluye con un salto de línea invisible, ubicando la siguiente salida en el renglón de abajo.'),
    ('duel_m09_q06', 9, 1, 'Toda llamada a una función debe abrir y cerrar sus paréntesis correspondientes. Omitir el cierre genera un error de sintaxis.'),
    ('duel_m09_q07', 9, 2, 'Python evalúa la expresión aritmética 10 * 3 + 2 = 32 y luego la imprime precedida del texto literal separado por un espacio.'),
    ('duel_m09_q08', 9, 3, 'Primero imprime ''Inicio con: 3''. Luego vidas pasa a valer 2. Finalmente imprime ''Quedan: 2''.'),
    ('duel_m10_q01', 10, 0, 'La función input() siempre lee y entrega la información como una cadena de texto (str), aun cuando el usuario solo haya ingresado dígitos numéricos.'),
    ('duel_m10_q02', 10, 1, 'El texto dentro de input() es el mensaje guía o ''prompt'' que se exhibe al usuario para indicarle qué dato se espera recibir.'),
    ('duel_m10_q03', 10, 2, 'Como no se realizó conversión, a guarda ''4'' y b guarda ''5''. El operador + entre textos los concatena, produciendo ''45''.'),
    ('duel_m10_q04', 10, 3, 'La función int() convierte los textos ''6'' y ''7'' en los enteros 6 y 7. La multiplicación matemática es 6 * 7 = 42.'),
    ('duel_m10_q05', 10, 0, 'Para interpretar y almacenar números con parte decimal es necesario utilizar la función de conversión float().'),
    ('duel_m10_q06', 10, 1, 'edad contiene una cadena de texto. Intentar sumarle el entero 1 produce un TypeError por incompatibilidad de tipos.'),
    ('duel_m10_q07', 10, 2, 'La función int() exige que la cadena esté formada estrictamente por dígitos numéricos (''5''). Si recibe letras, falla la conversión.'),
    ('duel_m10_q08', 10, 3, 'edad se convierte a 15. edad_proxima = 15 + 1 = 16. print() muestra el texto seguido de 16.'),
    ('duel_m11_q01', 11, 0, 'La condición 120 > 100 es verdadera (True), por lo que se ejecuta la instrucción indentada dentro del bloque if.'),
    ('duel_m11_q02', 11, 1, 'La condición 80 > 100 es False. El bloque if no se ejecuta. El programa continúa con la siguiente instrucción fuera del if.'),
    ('duel_m11_q03', 11, 2, 'La condición compra <= saldo evalúa 300 <= 500 (True). Se entra al if: saldo pasa a valer 500 - 300 = 200 y se imprime el mensaje con 200. El bloque else no se ejecuta.'),
    ('duel_m11_q04', 11, 3, 'temperatura >= 20 es 10 >= 20 (False). Al ser falsa la condición del if, el flujo pasa directamente al bloque else e imprime ''Fresco''.'),
    ('duel_m11_q05', 11, 0, 'La primera condición (7 >= 9) es False. Se evalúa el elif: (7 >= 6) es True. Se ejecuta su bloque (''Aprobado'') y finaliza la estructura condicional.'),
    ('duel_m11_q06', 11, 1, 'En Python, las cabeceras de estructuras de control como if, elif, else deben terminar obligatoriamente con el carácter de dos puntos (:).'),
    ('duel_m11_q07', 11, 2, 'En Python los bloques de código no usan llaves sino sangría (indentación). El cuerpo del if debe tener sangría hacia la derecha.'),
    ('duel_m11_q08', 11, 3, 'Entra al primer if porque es_fin_de_semana es True. Dentro, evalúa hay_sol: como es False, va al else interno e imprime ''Cine''.'),
    ('duel_m12_q01', 12, 0, 'Los bucles permiten automatizar la repetición de tareas e instrucciones de forma controlada y eficiente.'),
    ('duel_m12_q02', 12, 1, 'Todo ciclo debe tener un mecanismo o condición de parada que garantice su terminación y evite una ejecución infinita.'),
    ('duel_m12_q03', 12, 2, 'Un bucle infinito se produce cuando la condición de permanencia se mantiene en True indefinidamente, impidiendo que el programa avance.'),
    ('duel_m12_q04', 12, 3, 'Un contador registra cuántas iteraciones se han realizado y suele formar parte de la condición que determina el fin del ciclo.'),
    ('duel_m12_q05', 12, 0, 'La instrucción print(''Listo'') no está indentada, lo que indica que está fuera del bucle. Por ende, se ejecuta una única vez al finalizar el for.'),
    ('duel_m12_q06', 12, 1, 'La condición inicial 10 < 5 es falsa (False) desde el comienzo, por lo que el cuerpo del ciclo no se ejecuta ni una sola vez. Se imprime directamente ''Afuera''.'),
    ('duel_m12_q07', 12, 2, 'contador toma sucesivamente los valores 0, 1, 2, 3 (4 iteraciones en total). Cuando llega a 4, la condición 4 < 4 es False y se detiene.'),
    ('duel_m12_q08', 12, 3, 'En la vuelta 3, i se incrementa a 4. Al volver a evaluar la condición (4 <= 3), resulta False y el bucle termina. El valor de i al salir es 4.'),
    ('duel_m13_q01', 13, 0, 'range(3) genera la secuencia de números enteros comenzando en 0 y terminando en n-1: 0, 1 y 2.'),
    ('duel_m13_q02', 13, 1, 'range(5) genera 5 elementos (0, 1, 2, 3, 4), por lo que el cuerpo del ciclo se repite exactamente 5 veces.'),
    ('duel_m13_q03', 13, 2, 'Cuando range recibe dos argumentos (inicio, fin), comienza en ''inicio'' y llega hasta ''fin - 1''. Aquí genera 2, 3 y 4.'),
    ('duel_m13_q04', 13, 3, 'El tercer parámetro es el paso (incremento). Comienza en 1 y avanza de 2 en 2 mientras sea menor a 8: 1, 3, 5 y 7.'),
    ('duel_m13_q05', 13, 0, 'i toma los valores 1, 2, 3. suma = 0 + 1 = 1; luego 1 + 2 = 3; luego 3 + 3 = 6. Se imprime 6 al salir del bucle.'),
    ('duel_m13_q06', 13, 1, 'Al igual que en las estructuras condicionales, la cabecera del bucle for debe terminar obligatoriamente con el carácter de dos puntos (:).'),
    ('duel_m13_q07', 13, 2, 'factor toma los valores 1, 2, 3, 4. producto = 1 * 1 = 1; luego 1 * 2 = 2; luego 2 * 3 = 6; luego 6 * 4 = 24. Imprime 24.'),
    ('duel_m13_q08', 13, 3, 'n recorre 1, 2, 3, 4, 5. La condición n % 2 == 0 es verdadera únicamente para 2 y 4 (2 números pares). Se imprime 2.'),
    ('duel_m14_q01', 14, 0, 'El bucle while repite su bloque mientras su condición sea verdadera. En el momento en que la condición evalúa a False, el ciclo se detiene.'),
    ('duel_m14_q02', 14, 1, 'c inicia en 1. Imprime 1 e incrementa a 2. Imprime 2 e incrementa a 3. Imprime 3 e incrementa a 4. Al ser 4 <= 3 falso, finaliza.'),
    ('duel_m14_q03', 14, 2, 'Imprime 3, luego 2, luego 1. Al restar a 0, la condición 0 > 0 es False. Sale del ciclo e imprime ''Despegue''.'),
    ('duel_m14_q04', 14, 3, 'Si dentro del cuerpo del while no se modifica la variable involucrada en la condición, esta nunca cambiará y el ciclo se ejecutará infinitamente.'),
    ('duel_m14_q05', 14, 0, 'n=1: total = 0 + 10 = 10. n=2: total = 10 + 20 = 30. n=3: total = 30 + 30 = 60. n pasa a 4 y sale. Imprime 60.'),
    ('duel_m14_q06', 14, 1, 'print(''Fin'') está al mismo nivel que el while (sin sangría), lo que significa que está fuera del bucle. Solo se ejecuta una vez al terminar.'),
    ('duel_m14_q07', 14, 2, 'Inicial: valor = 1. Vuelta 1: valor = 1 * 3 = 3 (< 20). Vuelta 2: valor = 3 * 3 = 9 (< 20). Vuelta 3: valor = 9 * 3 = 27 (no es < 20, sale). Imprime 27.'),
    ('duel_m14_q08', 14, 3, 'Inicio: a=0, b=10 (0<10). Vuelta 1: a=2, b=9 (2<9). Vuelta 2: a=4, b=8 (4<8). Vuelta 3: a=6, b=7 (6<7). Vuelta 4: a=8, b=6 (8<6 es False, sale). Imprime 8 6.'),
    ('duel_m15_q01', 15, 0, 'total = 4 * 25 = 100. La función print() muestra el texto literal seguido de un espacio y el número 100.'),
    ('duel_m15_q02', 15, 1, 'Como 1200 > 1000 es True, descuento = 200. Luego total = 1200 - 200 = 1000. Se imprime 1000.'),
    ('duel_m15_q03', 15, 2, 'puntos >= 100 es False. Se evalúa elif puntos >= 50: 65 >= 50 es True. Asigna cat = ''Plata'' e imprime.'),
    ('duel_m15_q04', 15, 3, 'Las notas mayores o iguales a 4 son: 4, 8 y 7 (3 notas). El contador aprobados se incrementa 3 veces. Se imprime 3.'),
    ('duel_m15_q05', 15, 0, 'La instrucción print(total) aparece en la primera línea, antes de que total haya sido calculada y definida, violando el orden lógico de ejecución.'),
    ('duel_m15_q06', 15, 1, '500 >= 350 es True. Entra al if: vuelto = 500 - 350 = 150. Se imprime ''Vuelto: 150''.'),
    ('duel_m15_q07', 15, 2, '45 > 78 es False. Se ejecuta la rama else, asignando mayor = num2 (78). Se imprime ''El mayor es: 78''.'),
    ('duel_m15_q08', 15, 3, 'Mes 1: ahorro=50. Mes 2: ahorro=100. Mes 3: ahorro=150. Al llegar a 150, la condición (150 < 150) es False y sale. meses vale 3.')
ON CONFLICT (id) DO UPDATE SET
    module_id = EXCLUDED.module_id,
    correct_answer = EXCLUDED.correct_answer,
    explanation = EXCLUDED.explanation;

-- 3. Verificación de seguridad RLS
ALTER TABLE public.online_questions_truth ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.online_questions_truth FROM anon, PUBLIC;
GRANT SELECT ON TABLE public.online_questions_truth TO authenticated;
